### ISSUE TITLE
Connection pool is full, discarding connection: 

### ISSUE THREAD

**Issue by s2tu** [TracyWebTech/django-revproxy#97]
I am trying to create a reverse proxy to a internal website.  It works for the most part however one endpoint I get the following warning:

WARNING  [2019-01-29 15:46:27,893] [none] urllib3.connectionpool: Connection pool is full, discarding connection: 127.0.0.1

I assume somewhere in the code I can increase the pool size limit but do I need to make this change?

**Comment by seocam** [comment]
Getting a full pool shouldn't be a problem. We use the pool to minimize the overhead of creating too many connections. The pool manager has 10 slots and the LRU connection is dropped as soon as a new connection is created. You should have 1 connection per upstream. How many upstreams you currently have?

We currently don't have a variable to change that value. 
That's where the PoolManager is instantiated: https://github.com/TracyWebTech/django-revproxy/blob/master/revproxy/views.py#L34

Here are the docs for the PoolManager: https://urllib3.readthedocs.io/en/1.2.1/managers.html

Are you experiencing any issues because of that?

**Comment by s2tu** [comment]
Yeah I managed to resolve this issue without modifying the revproxy by following the below link:

https://stackoverflow.com/questions/18466079/can-i-change-the-connection-pool-size-for-pythons-requests-module

Thanks for the reply!

**Comment by brianmay** [comment]
Just curious: how many slots do you need? What issues is this causing - not counting the warning message - which I believe is just warning?
